(()=>{'use strict';const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function db(op){const r=await fetch('/api/db',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(op)}),j=await r.json();if(!r.ok)throw Error(j.error||'操作失败');return j.data||[]}
function toast(s){const n=$('#toast');n.textContent=s;n.hidden=false;setTimeout(()=>n.hidden=true,2400)}function close(){$('#modal').hidden=true;document.body.style.overflow=''}
function open(){const panel=$('#modalPanel');panel.className='modal-panel reader';panel.innerHTML=`<div class="editor sentence-picker"><div class="modal-head"><div><p class="eyebrow">WORDS FROM CONTEXT</p><h2>从例句中选择单词</h2></div><button class="close" type="button" data-close>×</button></div><p>粘贴题目中的英文句子，勾选需要积累的词，再填写或自动生成竞赛语境下的释义。</p><textarea id="sentenceInput" rows="6" placeholder="You are given a permutation of n distinct integers..."></textarea><div class="editor-actions"><button type="button" class="ghost" id="analyzeSentence">识别候选词</button></div><div id="wordCandidates" class="word-candidates"></div><div class="editor-actions" id="candidateActions" hidden><button type="button" class="ghost" id="aiMeanings">AI 生成释义</button><button type="button" class="action primary" id="saveCandidates">确认加入词库</button></div></div>`;$('#modal').hidden=false;document.body.style.overflow='hidden';let sentence='';
$('#analyzeSentence').onclick=()=>{sentence=$('#sentenceInput').value.trim();const stop=new Set('the a an and or but if then else is are was were be been being of to in on at for from with by as this that these those you your we our it its given each any all can will should must have has had not no yes into over under than such where when which who whose there here find determine output input print read return using use'.split(' ')),words=[...new Set((sentence.match(/[A-Za-z][A-Za-z'-]{2,}/g)||[]).map(x=>x.toLowerCase()).filter(x=>!stop.has(x)))];$('#wordCandidates').innerHTML=words.map(w=>`<label class="candidate-row"><input type="checkbox" checked><b>${esc(w)}</b><input data-pos placeholder="词性"><input data-meaning placeholder="中文释义"></label>`).join('')||'<p class="empty">没有识别到候选词</p>';$('#candidateActions').hidden=!words.length};
$('#aiMeanings').onclick=async()=>{const rows=$$('.candidate-row').filter(r=>r.querySelector('input[type=checkbox]').checked),words=rows.map(r=>r.querySelector('b').textContent);if(!words.length)return;const btn=$('#aiMeanings');btn.disabled=true;btn.textContent='生成中…';try{const prompt='结合这句算法竞赛题面，为这些英文单词给出词性和简洁中文释义。只返回 JSON 数组，字段 word,pos,meaning。句子：'+sentence+'\n单词：'+words.join(', '),r=await fetch('/api/ai',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'auto',messages:[{role:'user',content:prompt}],stream:true})});if(!r.ok)throw Error('AI 服务暂时不可用');const raw=await r.text();let out='';raw.split(/\r?\n/).filter(x=>x.startsWith('data:')).forEach(line=>{try{out+=JSON.parse(line.slice(5)).choices?.[0]?.delta?.content||''}catch{}});const parsed=JSON.parse((out.match(/\[[\s\S]*\]/)||[])[0]||'[]');rows.forEach(row=>{const item=parsed.find(x=>String(x.word).toLowerCase()===row.querySelector('b').textContent);if(item){row.querySelector('[data-pos]').value=item.pos||'';row.querySelector('[data-meaning]').value=item.meaning||''}})}catch(e){toast('自动释义失败，可以直接手动填写')}finally{btn.disabled=false;btn.textContent='AI 生成释义'}};
$('#saveCandidates').onclick=async()=>{const data=$$('.candidate-row').filter(r=>r.querySelector('input[type=checkbox]').checked).map(r=>({word:r.querySelector('b').textContent,pos:r.querySelector('[data-pos]').value.trim(),meaning:r.querySelector('[data-meaning]').value.trim()||'待补充',examples:sentence,note:''}));if(!data.length)return;try{await db({table:'words',action:'insert',columns:'*',filters:{},data,returning:true});close();toast(`已从例句加入 ${data.length} 个单词`);setTimeout(()=>location.reload(),350)}catch(e){toast(e.message)}}}
document.addEventListener('click',e=>{if(e.target.closest('[data-pick-words]')){e.preventDefault();e.stopImmediatePropagation();open()}},true);
})();
