INSERT INTO words (word, pos, meaning, examples, note) VALUES
('hack','v.','破解（比赛术语：hack 他人代码）',$jq$["You can hack only if you solved all versions of this problem."]$jq$::jsonb,''),
('arbitrary','adj.','任意的',$jq$["choose an arbitrary integer m"]$jq$::jsonb,''),
('denote','v.','表示，代表',$jq$["Here, gcd(x,y) denotes the greatest common divisor (GCD) of integers x and y."]$jq$::jsonb,''),
('portal','n.','大门，入口；（题中常指）传送门',$jq$["There are also two portals located at positions x and y (x<y)."]$jq$::jsonb,''),
('respectively','adv.','分别地',$jq$["Using operation 1 on the left and right portals respectively results in the arrays [0,2,4,0,3,1] and [3,0,4,2,0,1]."]$jq$::jsonb,''),
('lexicographically','adv.','按字典序地',$jq$["Find the lexicographically smallest permutation you can obtain using these operations."]$jq$::jsonb,''),
('lexicon','n.','词典，词汇表',$jq$[]$jq$::jsonb,'lexicographically（字典序地）的同根词'),
('index','n.','索引，下标（复数 indices / indexes）',$jq$["A permutation a is lexicographically smaller than permutation b if there exists an index i such that aj=bj for all indices 1<=j<i and ai<bi."]$jq$::jsonb,'原题笔记里写成 indice，正确单数是 index，复数是 indices/indexes'),
('optimal','adj.','最优的',$jq$["In the fourth test case, it is optimal not to do any operations."]$jq$::jsonb,''),
('compute','v.','计算',$jq$["you must compute a value for one sequence"]$jq$::jsonb,''),
('terminate','v.','终止，结束',$jq$["If k=0, terminate immediately and return the sequence x."]$jq$::jsonb,''),
('immediately after','phr.','紧挨着，紧接着……之后',$jq$["Then, select any index 1<=i<=|x| and insert (xi+1) immediately after the element xi."]$jq$::jsonb,''),
('infer','v.','推断，推测',$jq$["but it is not an easy job to infer the input from the output of the algorithm."]$jq$::jsonb,''),
('separate','adj.','单独的，分开的',$jq$["For each test case, output the length of the shortest sequence on a separate line."]$jq$::jsonb,''),
('prefix','n.','前缀',$jq$["x is a prefix of y, but x!=y"]$jq$::jsonb,''),
('corresponding','adj.','对应的',$jq$["the array x has a smaller element than the corresponding element in y."]$jq$::jsonb,''),
('product','n.','乘积；（也指）产品',$jq$["Let f(a) denote the number of subarrays of a whose product is divisible by 6."]$jq$::jsonb,''),
('divisible','adj.','可整除的',$jq$["Let f(a) denote the number of subarrays of a whose product is divisible by 6."]$jq$::jsonb,'be divisible by ... 可被……整除'),
('palindrome','n.','回文',$jq$["A palindrome is a string that reads the same backward as forward, for example, strings \"z\", \"aaa\", \"aba\", \"abccba\" are palindromes, but strings \"codeforces\", \"reality\", \"ab\" are not."]$jq$::jsonb,''),
('positive integer','n.','正整数',$jq$["A positive integer x is a perfect root if there exists an integer y such that y=sqrt(x)."]$jq$::jsonb,''),
('frosting','n.','（蛋糕上的）糖霜',$jq$["so the frosting on the cake is uneven"]$jq$::jsonb,''),
('uneven','adj.','不平坦的，不均匀的',$jq$["so the frosting on the cake is uneven"]$jq$::jsonb,''),
('level','v./adj.','使平整；水平的',$jq$["To quickly solve this issue, Alice will put her knife at some integer height and then sweep the frosting from left to right to make the frosting level."]$jq$::jsonb,''),
('bracket','n.','括号',$jq$["We say that a bracket sequence a is better than a bracket sequence b if one of the following holds:"]$jq$::jsonb,''),
('arithmetic','n.','算术',$jq$["A regular bracket sequence is a bracket sequence that can be transformed into a correct arithmetic expression by inserting the characters 1 and + between the original characters of the sequence."]$jq$::jsonb,''),
('hourglass','n.','沙漏',$jq$["Vadim's hourglass measures s minutes."]$jq$::jsonb,''),
('errand','n.','差事，跑腿',$jq$["However, Vadim needs to leave for errands in m minutes"]$jq$::jsonb,'原句中是复数 errands，词条取原形'),
('proceed','v.','继续进行',$jq$["After this, the game proceeds to the next turn, or ends if it is the n-th turn."]$jq$::jsonb,''),
('if and only if','phr.','当且仅当',$jq$["we call it complete if and only if both of the following hold:"]$jq$::jsonb,'常缩写为 iff'),
('ascending','adj.','升序的',$jq$["Stepan wants to know whether it is possible to sort the permutation in ascending order using any number of such operations."]$jq$::jsonb,''),
('lowercase','n./adj.','小写（字母）',$jq$["You may output each letter in any case (lowercase or uppercase). For example, the strings \"yEs\", \"yes\", \"Yes\", and \"YES\" will be accepted."]$jq$::jsonb,''),
('garland','n.','花环，彩灯串',$jq$["Masha has a New Year garland consisting of n bulbs."]$jq$::jsonb,''),
('bulb','n.','灯泡',$jq$["Masha has a New Year garland consisting of n bulbs"]$jq$::jsonb,''),
('binary','adj.','二进制的',$jq$["The state of the garland is given by a binary string s of length n, where '0' denotes an off bulb and '1' denotes an on bulb."]$jq$::jsonb,''),
('adjacent','adj.','相邻的',$jq$["Masha considers the garland beautiful if the states of adjacent bulbs strictly alternate.", "For each 1<=i<n, positions i and i+1 are adjacent, and positions 1 and n are also adjacent."]$jq$::jsonb,''),
('alternate','adj./v.','交替的；交替，轮流',$jq$["Masha considers the garland beautiful if the states of adjacent bulbs strictly alternate."]$jq$::jsonb,''),
('subsegment','n.','子段',$jq$["Yura can apply the following operation to the garland: choose a subsegment and flip the state of all bulbs in it, that is, turn all on bulbs off and all off bulbs on."]$jq$::jsonb,'subarray 是子数组，subsegment 多见于字符串/序列题'),
('takeout','n.','外卖',$jq$["A. Marisa Steals Reimu's Takeout"]$jq$::jsonb,''),
('safeguard','v.','保护，保卫',$jq$["Marisa is a girl of integrity who always helps others safeguard their belongings."]$jq$::jsonb,''),
('fondness','n.','喜爱，癖好',$jq$["Marisa has a special fondness for the number 3."]$jq$::jsonb,''),
('concatenate','v.','连接，拼接',$jq$["Delete and Concatenate", "After each operation, the remaining elements are concatenated without changing their relative order."]$jq$::jsonb,''),
('relative','adj.','相对的',$jq$["After each operation, the remaining elements are concatenated without changing their relative order."]$jq$::jsonb,''),
('subtract','v.','减去',$jq$["Every time you perform an operation (regardless of the type), c is subtracted from your score."]$jq$::jsonb,'原句是 subtracted，词条取原形'),
('partition','n./v.','划分，分区',$jq$["Given an array a, let f(a) be the number of ways to partition a into one or more subarrays such that:"]$jq$::jsonb,'')
ON CONFLICT (word) DO NOTHING